Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace SampleMvcApp.Controllers
{
    public class AccountController : Controller
    {
        public async Task Login(string returnUrl = "/")
        {
            await HttpContext.ChallengeAsync("Auth0", new AuthenticationProperties() { RedirectUri = returnUrl });
        }

        [Authorize]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Auth0", new AuthenticationProperties
            {
                // Indicate here where Auth0 should redirect the user after a logout.
                // Note that the resulting absolute Uri must be whitelisted in the 
                // **Allowed Logout URLs** settings for the client.
                RedirectUri = Url.Action("Index", "Home")
            });
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        /// <summary>
        /// This is just a helper action to enable you to easily see all claims related to a user. It helps when debugging your
        /// application to see the in claims populated from the Auth0 ID Token
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public IActionResult Claims()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Controllers/ChatroomController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using SampleMvcApp.Model;

namespace SampleMvcApp.Controllers
{
    [Authorize]
    public class ChatroomController : Controller
    {
        private readonly IDistributedCache _distributedCache;
        public ChatAppDbContext _chatAppDbContext;

        public ChatroomController(IDistributedCache distributedCache, ChatAppDbContext chatAppDbContext)
        {
            _distributedCache = distributedCache;
            _chatAppDbContext = chatAppDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetChatHistory([FromQuery]string receipient)
        {
            var currentChat = await _chatAppDbContext.Chat.FirstOrDefaultAsync(a => (a.SenderId == User.Identity.Name && a.RecipientId == receipient) || (a.SenderId == receipient && a.RecipientId == User.Identity.Name));

            var cacheKey = "chatHistory";
            string serializedChatHistory;
            var chatHistory = new List<Message>();
            byte[] redisChatHistory = await _distributedCache.GetAsync(cacheKey);

            if (redisChatHistory != null && redisChatHistory.Length>0)
            {
                serializedChatHistory = Encoding.UTF8.GetString(redisChatHistory);
                chatHistory = JsonConvert.DeserializeObject<List<Message>>(serializedChatHistory);
            }
            else
            {
                
                chatHistory = await _chatAppDbContext.Messages
                    .Where(a => currentChat != null && a.ChatId == currentChat.Id).ToListAsync();
                
                serializedChatHistory = JsonConvert.SerializeObject(chatHistory);
                redisChatHistory = Encoding.UTF8.GetBytes(serializedChatHistory);
                var options = new DistributedCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromSeconds(30))
                    .SetSlidingExpiration(TimeSpan.FromSeconds(10));
                await _distributedCache.SetAsync(cacheKey, redisChatHistory, options);
            }
            return Json(chatHistory);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Globalization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace SampleMvcApp.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            // If the user is authenticated, then this is how you can get the access_token and id_token
            if (User.Identity.IsAuthenticated)
            {
                string accessToken = await HttpContext.GetTokenAsync("access_token");

                // if you need to check the access token expiration time, use this value
                // provided on the authorization response and stored.
                // do not attempt to inspect/decode the access token
                DateTime accessTokenExpiresAt = DateTime.Parse(
                    await HttpContext.GetTokenAsync("expires_at"),
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.RoundtripKind);

                string idToken = await HttpContext.GetTokenAsync("id_token");

                // Now you can use them. For more info on when and how to use the
                // access_token and id_token, see https://auth0.com/docs/tokens
            }

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Chatroom/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title> Chat App </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Chat" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" />

</head>

<body>


    <div class="page-wrapper" id="chatApp">

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box">
                            <div class="row">


                            </div><!--end row-->
                        </div>
                    </div><!--end col-->
                </div>

                <div class="row">
                    <div class="col-12">

                        <div class="chat-box-left overflow-auto" style="height: 600px">
                            <ul class="nav nav-pills mb-3 nav-justified" id="pills-tab" role="tablist">
                            </ul>

                            <div data-simplebar>
                                <div class="tab-content chat-list" id="pills-tabContent">
                                    <div class="tab-pane fade show active" id="general_chat">

                                        <a href="#" class="media new-message" v-on:click="setCurrentRecipient(chatuser)" v-for="chatuser in onlineUsers" :key="chatuser.connectionId">
                                            <div class="media-left">
                                                <img src="https://res.cloudinary.com/rhyoliteprime/image/upload/v1533814738/images_6.png" alt="" class="rounded-circle thumb-md">
                                                <span class="round-10 bg-success"></span>
                                            </div>
                                            <div class="media-body">
                                                <div class="d-inline-block">
                                                    <h6> {{chatuser.username }} </h6>
                                                </div>

                                            </div>
                                        </a>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="chat-box-right overflow-auto" style="height: 600px">
                            <div class="chat-header">
                                <a href="#" class="media">
                                    <div class="media-left">
                                        <img src="assets/images/users/user-4.jpg" alt="user" class="rounded-circle thumb-md">
                                    </div><!-- media-left -->
                                    <div class="media-body">
                                        <div>
                                            <h6 class="m-0"> @User.Identity.Name    </h6>
                                            <p class="mb-0"> Online </p>
                                        </div>
                                    </div>
                                </a>
                                <div class="chat-features">
                                    <div class="d-none d-sm-inline-block">

                                    </div>
                                </div>
                            </div>
                            <div class="chat-body" data-simplebar>
                                <div class="chat-detail overflow-auto" v-for="msg in messages" :key="msg.id">

                                    <div class="media" v-if="msg.type==0">
                                        <div class="media-img">
                                            <img src="https://res.cloudinary.com/rhyoliteprime/image/upload/v1533814738/images_6.png" alt="user" class="rounded-circle thumb-md">
                                        </div>
                                        <div class="media-body">
                                            <div class="chat-msg">
                                                <p> {{msg.msgContent}} </p>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="media" v-if="msg.type==1">
                                        <div class="media-body reverse">
                                            <div class="chat-msg">
                                                <p> {{msg.msgContent}} </p>
                                            </div>

                                        </div>
                                        <div class="media-img">
                                            <img src="https://res.cloudinary.com/rhyoliteprime/image/upload/v1533814738/images_6.png" alt="user" class="rounded-circle thumb-md">
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="chat-footer">
                                <div class="row">
                                    <div class="col-12 col-md-9">
                                        <span class="chat-admin"><img src="assets/images/users/user-4.jpg" alt="user" class="rounded-circle thumb-sm"></span>
                                        <input type="text" class="form-control" v-model="userMessage" placeholder="Type something here..." v-on:keyup.13="sendMsg">
                                    </div><!-- col-8 -->
                                    <div class="col-3 text-right">
                                        <div class="d-none d-sm-inline-block chat-features">

                                            <a href="#"><i class="fas fa-paper-plane" v-on:click="sendMsg"></i></a>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </div>

    </div>

    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/feather.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="~/js/signalr.js"></script>

</body>


</html>

<script>

   var app = new Vue({
                el: "#chatApp",
                data: {
                    userName: '@User?.Identity.Name',
                    userMessage: "",
                    connection: "",
                    messages: [],
                    onlineUsers: [],
                    errorMessage: null,
                    currentRecipient: "",
                    currentRecipientConnectionId: "",

                 },
            methods: {
                sendMsg: function (event) {
                    if (this.userName && this.userMessage && this.currentRecipient) {
                        // ---------
                        //  Call hub methods from client
                        // ---------
                        console.log("....");
                        var senderId = this.userName;
                        var msgContent = this.userMessage;
                        var id = Math.random();
                        this.messages.push({ senderId, msgContent,id,type:1 });
                        this.connection
                            .invoke("SendMessage", this.userName, this.currentRecipient, this.userMessage)
                            .catch(function(err) {
                                return console.error(err.toSting());
                            });

                        this.userMessage = "";
                    }
                    else if(this.userName==""){
                        this.errorMessage = "User not Logged in";
                    }
                    else if (this.currentRecipient == "") {
                        this.errorMessage = "Select a recipient to send message.";
                    }
                },
                setCurrentRecipient(userInfo) {

                    this.currentRecipient = userInfo.username;
                    this.currentRecipientConnectionId = userInfo.connectionId;
                },
                getChatHistory() {

                    return axios.get('/ChatRoom/GetChatHistory?receipient=' + this.currentRecipient).then(response => response.data);

                },

            },
            created: function() {

                this.connection = new signalR.HubConnectionBuilder()
                    .withUrl("/chatHub")
                    .configureLogging(signalR.LogLevel.Information)
                    .build();
                this.connection.start().catch(function(err) {
                    return console.error(err.toSting());
                });

                if (this.currentRecipient !="") {

                    this.getChatHistory()
                        .then(data => {

                            data.forEach(  ( v )=>
                            {
                                if (v.senderId === this.userName) {
                                    v.type = 1;
                                }
                                else {
                                    v.type = 0;
                                }

                            });

                            this.messages = data;
                            console.log("data", data);
                            console.log("messages",this.messages);

                        })
                        .catch(err => console.log(err));
                }


                //connection.start()
                //    .then(() => connection.invoke("send", "Hello"));

            },
            mounted: function() {


                this.connection.on("ReceiveMessage", (senderId, msgContent)=> {
                    console.log("message received", msgContent);
                    this.messages.push({ senderId, msgContent, type: 0  });
                });

                this.connection.on("UpdateOnlineUsers",  (onlineusers)=> {
                    console.log(onlineusers);
                    var filteredArray = onlineusers.filter( (u)=> {
                        return u.username !=this.userName;

                    });

                    if (filteredArray.length > 0) {

                        this.currentRecipient = filteredArray[0].username;
                        this.currentRecipientConnectionId = filteredArray[0].connectionId;

                        this.getChatHistory()
                            .then(data => {

                                data.forEach((v) => {
                                    if (v.senderId === this.userName) {
                                        v.type = 1;
                                    } else {
                                        v.type = 0;
                                    }

                                });

                                this.messages = data;

                            })
                            .catch(err => console.log(err));
                    }
                    else {
                        this.messages = [];
                    }
                    this.onlineUsers = filteredArray;
                });

            }
        });

</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h2> Signalr Chat App With VueJs </h2>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chat App</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">   </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        
                        <li><a id="">@User.Identity.Name  </a></li>
                        <li><a id="" asp-controller="Chatroom" asp-action="Index">Chat room</a></li>

                        <li><a id="qsLogoutBtn" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

<partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Chat App </p>
        </footer>
    </div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/assets/js/feather.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="~/js/signalr.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>